Add "safe" filter à la Nunjucks
oscarotero/vento pull request #20
Opened 2023-09-18 18:14 UTC by dz4k

Per Discord discussion:

> dz4k — Yesterday at 10:51 PM \
> @Óscar there should be a filter like `trustHtml` that simply marks text as trusted without transforming it, and the docs should be updated to recommend that when autoescaping is used. Happy to PR
>
> Óscar — Yesterday at 11:00 PM \
> I see.
>
> Ok, maybe `safe`, like Nunjucks.

Note: I never liked the `safe` name but it might be better to keep it for familiarity.

2023-09-18 19:38 UTC, oscarotero requested changes
I'm open to pick a different name, but I wouldn't mention `html` here (like your proposal `trustHtml`) because you may want to escape non-HTML code.

Maybe `no_autoescape` is more clear in its purpose, but it's also more longer.

2023-09-18 19:38 UTC, oscarotero commented on src/environment.ts
> +        if (name === "unescape" || name === "safe") {
I think only `safe` filter should be taken into account here and treat `unescape` as any other filter, without any special behavior.

2023-09-18 19:38 UTC, oscarotero commented on src/environment.ts
>            unescaped = true;
If we include a `continue` here, we no need to create a plugin with an empty function. `safe` can be considered a core feature of Vento, in the same way as `autoescape` option.

2023-09-21 16:05 UTC, oscarotero commented
Hi @dz4k 
Looks like there're some conflicts due the latest changes in the documentation.
Can you fix them? I also left a couple of suggestions to simplify your changes. Let me know if you have any question.
Thanks!

2023-09-22 08:38 UTC, dz4k commented
@oscarotero just got around to making those changes. Any final verdict on the filter name? maybe `noescape` or `trust`, or stick with `safe`?

BTW: 

> because you may want to escape non-HTML code.

It would be cool if the `autoescape` filter accepted an escaping function, so we could use Vento for templating other kinds of files without causing syntax errors -- maybe a future feature

2023-09-22 09:32 UTC, oscarotero commented
> Any final verdict on the filter name? maybe noescape or trust, or stick with safe?

`noescape` is confusing because you can combine it with `escape` filter: `{{ string | escape | noescape }}`.

If you don't like `safe`, I'm okay with `trust` (it's also short).
Let me know if you want to change it and when can I merge this.

> It would be cool if the autoescape filter accepted an escaping function, 

Maybe this function can be configurable in the options:

```js
const env = vento({
    autoescape: true, // use the default function
});

const env = vento({
    autoescape: (string) => string, // use a custom function
});
```

2023-09-23 13:54 UTC, dz4k commented
`safe` is fine, feel free to merge

2023-09-23 18:09 UTC, merged

2023-09-23 18:09 UTC, oscarotero commented
Great. Thanks!